---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cms-wildcard
  namespace: cert-manager
spec:
  isCA: false
  commonName: *.breeze-blocks.net
  secretName: wildcard-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: breeze-blocks-ca
    kind: ClusterIssuer
    group: cert-manager.io
