---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media00
  namespace: cert-manager
spec:
  isCA: false
  commonName: media00.breeze-blocks.net
  secretName: media00-tls
  dnsNames:
    - media00
    - media00.breeze-blocks.net
  ipAddresses:
    - 192.168.5.13
  emailAddresses:
    - media00@breeze-blocks.net
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: comms-svc-int
    kind: ClusterIssuer
    group: cert-manager.io
