---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
spec:
  isCA: true
  commonName: vault.breeze-blocks.net
  secretName: vault-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: the-hard-way-ca
    kind: ClusterIssuer
    group: cert-manager.io
