---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault
spec:
  isCA: true
  usages:
    - server auth
    - client auth
  # Avoid using commonName for DNS names in
  # end-entity (leaf) certificates. Unless you have a specific
  # need for it in your environment, use dnsNames exclusively to avoid issues with commonName.
  # Usually, commonName is used to give human-readable names to CA certificates and can be avoided for
  # other certificates.
  # commonName: vault.breeze-blocks.net
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: vault-tls
  subject:
    organizations:
      - cert-manager
      - breeze-blocks
      - the-hard-way
  issuerRef:
    name: the-hard-way-ca
    kind: ClusterIssuer
    group: cert-manager.io

  # The literalSubject field is exclusive with subject and commonName. It allows
  # specifying the subject directly as a string. This is useful for when the order
  # of the subject fields is important or when the subject contains special types
  # which can be specified by their OID.
  #
  # literalSubject: "O=jetstack, CN=example.com, 2.5.4.42=John, 2.5.4.4=Doe"

  # At least one of commonName (possibly through literalSubject), dnsNames, uris, emailAddresses, ipAddresses or otherNames is required.
  dnsNames:
    - vault.breeze-blocks.net
  uris:
    - https://vault.breeze-blocks.net
  emailAddresses:
    - duchess@breeze-blocks.net
  ipAddresses:
    - 192.168.5.82
  # Needs cert-manager 1.14+ and "OtherNames" feature flag
  # otherNames:
  #   # Should only supply oid of ut8 valued types
  #   - oid: 1.3.6.1.4.1.311.20.2.3 # User Principal Name "OID"
  #     utf8Value: upn@example.local
