apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cm.kubernetes.io/name: prometheus-scrapes
  name: prometheus-scrapes
data:
{{ (.Files.Glob "scrape-configs/prometheus-scrape*yaml").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cm.kubernetes.io/name: prometheus-config
  name: prometheus-config
data:
{{ (.Files.Glob "scrape-configs/prometheus-config.yaml").AsConfig | indent 2 }}
