controller:
  fullname: nginx
  enableCustomResources: true
  ingressClass:
    name: nginx
  nginxDebug: true
  service:
    externalIPs:
      - 192.168.5.50
  wildcardTLS:
    secret: nginx-tls
  nodeSelector:
    kuberenetes.io/os: linux
