apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: the-hard-way-int
  namespace: cert-manager
spec:
  ca:
    secretName: the-hard-way-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: the-hard-way-int
  namespace: cert-manager
spec:
  isCA: true
  commonName: int.the-hard-way.net
  secretName: the-hard-way-int
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: the-hard-way-ca
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
spec:
  isCA: true
  commonName: argo.breeze-blocks.net
  secretName: argocd-server-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: the-hard-way-ca
    kind: ClusterIssuer
    group: cert-manager.io
