apiVersion: v2
appVersion: v0.6.0
description: A Helm chart for the Valkey Operator
home: https://valkey.io/valkey-helm/
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
kubeVersion: '>=1.20.0-0'
maintainers:
- name: daanvinken
  url: https://github.com/daanvinken
- name: jdheyburn
  url: https://github.com/jdheyburn
- name: Bloodraven21
  url: https://github.com/Bloodraven21
name: valkey-operator
sources:
- https://github.com/valkey-io/valkey-operator.git
- https://valkey.io
type: application
version: 0.6.0
