apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: breeze-blocks-int
  namespace: nextcloud
spec:
  ca:
    secretName: breeze-blocks-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  isCA: false
  commonName: nextcloud.breeze-blocks.net
  secretName: breeze-blocks-int
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: breeze-blocks-int
    kind: Issuer
    group: cert-manager.io
