scrape_configs:
  - job_name: "postgres"
    scrape_interval: 5s
    static_configs:
      - targets:
          - "gitea.breeze-blocks.net:9187"
        labels:
          host: gitea.breeze-blocks.net
          hostname: gitea
          instance: gitea.breeze-blocks.net:9187
          job: postgres
          port: "9187"
          service: postgres-gitea
      - targets:
          - "grafana.breeze-blocks.net:9187"
        labels:
          host: grafana.breeze-blocks.net
          hostname: grafana
          instance: grafana.breeze-blocks.net:9187
          job: postgres
          port: "9187"
          service: postgres-grafana
      # - targets:
      #     - 'marius.breeze-blocks.net:9187'
      #   labels:
      #     host: marius.breeze-blocks.net
      #     hostname: marius
      #     instance: marius.breeze-blocks.net:9187
      #     job: postgres
      #     port: '9187'
      #     service: postgres-marius
      # - targets:
      #     - 'media.breeze-blocks.net:9187'
      #   labels:
      #     port: '9187'
      #     name: prometheus
      #     host: media
      - targets:
          - "nextcloud.breeze-blocks.net:9187"
        labels:
          host: nextcloud.breeze-blocks.net
          name: postgres
          port: "9187"
          service: nextcloud-postgres
      - targets:
          - "nautobot.breeze-blocks.net:9187"
        labels:
          host: nautobot.breeze-blocks.net
          hostname: nautobot
          job: postgres
          port: "9187"
          service: nautobot-postgres
      # - targets:
      #     - 'nextcloud.breeze-blocks.net:9187'
      #   labels:
      #     port: '9187'
      #     name: postgres
      #     host: nextcloud
      # - targets:
      #     - 'whac.breeze-blocks.net:9187'
      #   labels:
      #     port: '9187'
      #     name: postgres
      #     host: whac
