name: Lint Helm Charts
on:
  pull_request:
    branches:
      - main
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          submodules: "true"
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          check-latest: true
      - name: Lint Helm Charts
        run: |
          helm repo add frr https://metallb.github.io/frr-k8s
          helm repo update
          helm lint $(find . -type f | dirname $(grep Chart.yaml))
